export const communitySections = [
    {
        key: 'hero',
        title: 'Hero Section',
        description: 'Top campaign headline and CTA.',
        contentTitle: 'Together We Grow',
        heading: '$0.50 FROM EVERY PURCHASE YOU MAKE SUPPORTS GARMENT\'S WORKERS\' CHILDREN',
        sectionDescription: 'Every purchase makes a difference. We donate $0.50 from every order to support workers\' children in our community — helping create brighter futures through care, education, and opportunity.',
        buttonText: 'Let\'s Make a Purchase',
        buttonUrl: '/products',
        status: 'active',
    },
    {
        key: 'features',
        title: 'Impact Features',
        description: 'Education, care, and opportunity cards.',
        buttonText: 'Learn More',
        buttonUrl: '/about',
        status: 'active',
    },
    {
        key: 'community-center',
        title: 'Community Center',
        description: 'Programs and support initiatives section.',
        buttonText: 'Explore Programs',
        buttonUrl: '/community',
        status: 'active',
    },
    {
        key: 'gallery',
        title: 'Community Gallery',
        description: 'Moments from the community photo showcase.',
        buttonText: 'View Gallery',
        buttonUrl: '#gallery',
        status: 'active',
    },
    {
        key: 'newsletter',
        title: 'Newsletter',
        description: 'Email signup section at the end of page.',
        buttonText: 'Subscribe',
        buttonUrl: '#newsletter',
        status: 'active',
    },
];
